### ISSUE TITLE
Enhancement request: exclude specific functions  from a file

### ISSUE THREAD

**Issue by hemanthsridhar** [masakurapa/go-cover#12]
Thank you for creating this library. It is extremely useful to analyse coverage.
Can you please add an enhancement where we can exclude functions from a specific file.

**Comment by masakurapa** [comment]
@hemanthsridhar 

Thank you for your requests for enhancements.

We have released an option to exclude specific methods from coverage in `v0.11.0`.

You can exclude a function from a specific file, such as `(path/to/file.go).FuncName`.

Please see the [README](https://github.com/masakurapa/gover-html#-exclude-func) for several other ways to specify.

**Comment by hemanthsridhar** [comment]
with the new version v0.11.0 getting the below error. This is not happening v0.10.0

panic: interface conversion: ast.Expr is *ast.Ident, not *ast.StarExpr

goroutine 1 [running]:
github.com/masakurapa/gover-html/internal/cover.(*funcVisitor).Visit(0xc00021a7c0, {0x67bf50?, 0xc000214690})
	/go/pkg/mod/github.com/masakurapa/gover-html@v0.11.0/internal/cover/func.go:56 +0x4a7
go/ast.Walk({0x67b3f8?, 0xc00021a7c0?}, {0x67bf50?, 0xc000214690?})
	/usr/local/go/src/go/ast/walk.go:51 +0x5f
go/ast.walkDeclList({0x67b3f8, 0xc00021a7c0}, {0xc000030980?, 0x8, 0x6261c0?})
	/usr/local/go/src/go/ast/walk.go:38 +0x69
go/ast.Walk({0x67b3f8?, 0xc00021a7c0?}, {0x67bf00?, 0xc000473cb0?})
	/usr/local/go/src/go/ast/walk.go:366 +0x17ac
github.com/masakurapa/gover-html/internal/cover.findFuncs({0xc0000195c0, 0x22})
	/go/pkg/mod/github.com/masakurapa/gover-html@v0.11.0/internal/cover/func.go:93 +0xeb
github.com/masakurapa/gover-html/internal/cover.makeNewProfile(0xc000030800?, {0x67bb18, 0xc000030800})
	/go/pkg/mod/github.com/masakurapa/gover-html@v0.11.0/internal/cover/func.go:74 +0x2d
github.com/masakurapa/gover-html/internal/cover.toProfiles(0xc0000bdbe8, {0x67bb18, 0xc000030800})
	/go/pkg/mod/github.com/masakurapa/gover-html@v0.11.0/internal/cover/cover.go:107 +0x316
github.com/masakurapa/gover-html/internal/cover.ReadProfile({0x67b638, 0xc000012120}, {0x67bb18, 0xc000030800})
	/go/pkg/mod/github.com/masakurapa/gover-html@v0.11.0/internal/cover/cover.go:74 +0x656
main.main()
	/go/pkg/mod/github.com/masakurapa/gover-html@v0.11.0/gover.go:41 +0x19f

**Comment by hemanthsridhar** [comment]
@masakurapa
